### ISSUE TITLE
unable to create or add organism: 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/docker-compose-galaxy-annotation#5]
FYI @erasche   I think that this is an error in the wrapper somehow.  

The HTML error is:

```
HTTP Status 404 - /apollo/organism/index
```

This would be correct because there is no index method (or index.gsp) for organism.  It could be callsed as /apollo/organism/ as well, which will default to organism. 

It looks like the 'clientMethod' in self.request('<clientMethod>',data)  ignored.  Running "List Organisms" it fails the same way.  

The full error is this:

```
Fatal error: Exit code 1 ()
INFO:__main__:Determining if add or update required
INFO:__main__:  Adding Organism
Traceback (most recent call last):
  File "/galaxy-central/tools/apollo/create_or_update_organism.py", line 60, in <module>
    public=args.public
  File "/galaxy-central/tools/apollo/webapollo.py", line 550, in addOrganism
    return self.request('addOrganism', data)
  File "/galaxy-central/tools/apollo/webapollo.py", line 161, in request
    (r.status_code, r.text))
Exception: Unexpected response from apollo 404: <html><head><title>Apache Tomcat/7.0.69 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /apollo/organism/index</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/apollo/organism/index</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.69</h3></body></html>
```

**Comment by nathandunn** [comment]
findAllOrganisms seems to be broken as well.  This output as below.  With this command:

```
python /galaxy-central/tools/apollo/list_organisms.py $GALAXY_WEBAPOLLO_URL $GALAXY_WEBAPOLLO_USER $GALAXY_WEBAPOLLO_PASSWORD
```

```
final data {'username': 'admin@local.host', 'password': 'password'}
final url http://apollo:8080/apollo/organism/findAllOrganisms
```

**Comment by nathandunn** [comment]
I very explicitly put in the URL (username / password) for a known working server: 

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/shell/findAllOrganisms.sh

I get the same error, a 404, but stating the other server is not found :

```
/Apollo-staging/organism/index
```

```
final data {'username': 'ndunn@me.com', 'password': 'demo'}
final url http://icebox.lbl.gov/Apollo-staging/organism/findAllOrganisms
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /Apollo-staging/organism/index</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/Apollo-staging/organism/index</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>
Traceback (most recent call last):
  File "/galaxy-central/tools/apollo/list_organisms.py", line 12, in <module>
    print json.dumps(wa.organisms.findAllOrganisms(), indent=2)
  File "/galaxy-central/tools/apollo/webapollo.py", line 566, in findAllOrganisms
    return self.request('findAllOrganisms', {})
  File "/galaxy-central/tools/apollo/webapollo.py", line 174, in request
    (r.status_code, r.text))
Exception: Unexpected response from apollo 404: <!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /Apollo-staging/organism/index</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/Apollo-staging/organism/index</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>
```

**Comment by hexylena** [comment]
@nathandunn would you mind testing something for me? I've pushed https://github.com/TAMU-CPT/galaxy-apollo/commit/d8b684781db1e89563472be0fcc99400a35ebf85 should fix it.

I hit this issue in prod the other day, hadn't updated the tool suite for it yet.

Apollo used to just return a 200 OK with the data. Now it returns a 302 found (except with data in the body), and redirects to a non-existent URL returning a 404 as a result.

**Comment by hexylena** [comment]
(As usual, no rush. If it does fix it for you, feel free to hit merge on https://github.com/erasche/docker-galaxy-annotation/pull/1)

**Comment by nathandunn** [comment]
I believe I just fixed this in master (not pushed to docker hub though).  The 404's are weird though. I'll test both.

**Comment by hexylena** [comment]
Ok sounds good.

Here's what I'm seeing (on http://icebox.lbl.gov/Apollo-staging)

![utvalg_850](https://cloud.githubusercontent.com/assets/458683/16026215/694ed600-31bc-11e6-9e5c-918914134c44.png)

Note the:
- 302 found with a location block
- the json response as part of _this_ packet.

Here might be an easier to read view:

```
POST /Apollo-staging/organism/findAllOrganisms HTTP/1.1
Host: icebox.lbl.gov
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.10.0
Content-Type: application/json
Content-Length: 48

{"username": "ndunn@me.com", "password": "demo"}

HTTP/1.1 302 Found
Server: nginx/1.10.0
Date: Mon, 13 Jun 2016 23:12:44 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=F0BC24BA1397EDB3F2FBC18C201AD644; Path=/Apollo-staging/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/Apollo-staging; Max-Age=0; Expires=Sun, 12-Jun-2016 23:12:44 GMT
Location: http://icebox.lbl.gov/Apollo-staging/organism/index

453
[{"valid":true,"commonName":"Dog","blatdb":null,"annotationCount":0,"currentOrganism":false,"genus":null,"species":null,"id":167767,"sequences":3268,"directory":"/data/jbrowse/monarch/dog","publicMode":true},{"valid":true,"commonName":"Honeybee","blatdb":"/data/blat/amel-demo/db/amel.2bit","annotationCount":13,"currentOrganism":true,"genus":null,"species":null,"id":3836,"sequences":5644,"directory":"/data/jbrowse/data-amel-demo","publicMode":true},{"valid":true,"commonName":"Cow","blatdb":null,"annotationCount":0,"currentOrganism":false,"genus":null,"species":null,"id":517,"sequences":3317,"directory":"/data/jbrowse/cow","publicMode":true},{"valid":true,"commonName":"Cat","blatdb":null,"annotationCount":0,"currentOrganism":false,"genus":null,"species":null,"id":162253,"sequences":5500,"directory":"/data/jbrowse/monarch/cat/","publicMode":true},{"valid":true,"commonName":"Human-Hg38","blatdb":"/data/blat/hg38/hg38.2bit","annotationCount":0,"currentOrganism":false,"genus":"Homo","species":"sapiens","id":21,"sequences":486,"directory":"/data/jbrowse/human-GRCh38-v2-staging","publicMode":true}]
0

GET /Apollo-staging/organism/index HTTP/1.1
Host: icebox.lbl.gov
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.10.0
Content-Type: application/json
Cookie: JSESSIONID=F0BC24BA1397EDB3F2FBC18C201AD644

HTTP/1.1 404 Not Found
Server: nginx/1.10.0
Date: Mon, 13 Jun 2016 23:12:45 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Content-Language: en
Content-Encoding: gzip

1d1
.............N.0.._e.^X..$-.J...E..J.=pt.ib...v.vQ......H...D......?.'.........JF._...N8.,.x. ..-.#?..p.....W.......
...q.L1...Dp...g.......*...V...V.]..F..,3..3..
,..IK-.I.4.aZ...6.WU0..].....t.Y...8......K...D..
}1.o.........mo..
p...;}.`.1.qR..M..J=N+..........C.*...s(....E..."..8f.k....B.
M.J+L.JF!2...%].j.E..U........8_x....R..:^.U.mj..m.P.n= b..OPJn............-...))..{X....-Z...
..{.z.?.VhK#:'..3..............M. ............=.1.........s_..22..^.........
0
```

**Comment by nathandunn** [comment]
Sure.  I just fixed a lot of the 302's.   However, that redirect is still bizarre.   I'll test it locally before I retag.

**Comment by nathandunn** [comment]
When I run either of these it works:

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/shell/findAllOrganisms.sh

Not sure why it would have been issuing a redirect.   There was a bug where garbage might be returned if the user was incorrect, but that is now fixed.

**Comment by nathandunn** [comment]
I just updated staging.   Knock on wood that it works different for you now, though I think it should have been working before.

**Comment by hexylena** [comment]
Aye, absolutely no clue what's triggering the redirect, it's bloody odd and it didn't happen before. Maybe I'll hunt that down tomorrow.

If you've updated `/Apollo-staging/`, I just tested master and the previous commit for tamu-cpt/galaxy-webapollo and it still looks to require the latest commit. Given that the proposed change (accepting 302s on my end) is backwards compatible, I'll go ahead and merge that and hope for the best.

**Comment by nathandunn** [comment]
well, there was definitely a lot of redirect code in there before which I've fixed . . but it wouldn't have been triggered on yours

**Comment by nathandunn** [comment]
Had to do the same fix for updateUsers as well.

**Comment by nathandunn** [comment]
It all seems to be working now .

**Comment by nathandunn** [comment]
@erasche  You may want to rebuild against the newest gmod/apollo:latest  . . . but I think that this should be fine.
